[build]
  command = "pip install -r requirements.txt && python app.py"
  functions = "netlify_functions/"
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"
