[build]
  command = "pip install bardapi && python -m pip show bardapi > requirements.txt"
  functions = "netlify_functions/"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"
