[[redirects]]
  from = "/.netlify/functions/main"
  to = "/.netlify/functions/main"
  status = 200
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

